<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::insert([
            [
                'category_id'=>7,
                'supplier_id'=>6,
                'sku'=>'COMP-0001',
                'name'=>'Kingston 16GB DDR4 RAM',
                'description'=>'Desktop Memory Module',
                'cost_price'=>1800,
                'selling_price'=>2500,
                'stock'=>40,
                'reorder_level'=>8,
                'status'=>true,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'category_id'=>7,
                'supplier_id'=>6,
                'sku'=>'COMP-0002',
                'name'=>'Samsung 1TB SSD',
                'description'=>'NVMe SSD',
                'cost_price'=>3200,
                'selling_price'=>4200,
                'stock'=>25,
                'reorder_level'=>5,
                'status'=>true,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'category_id'=>6,
                'supplier_id'=>11,
                'sku'=>'NET-0001',
                'name'=>'TP-Link Gigabit Router',
                'description'=>'Dual Band WiFi Router',
                'cost_price'=>2100,
                'selling_price'=>2999,
                'stock'=>20,
                'reorder_level'=>5,
                'status'=>true,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'category_id'=>3,
                'supplier_id'=>4,
                'sku'=>'FUR-0001',
                'name'=>'Office Chair',
                'description'=>'Ergonomic Mesh Chair',
                'cost_price'=>3500,
                'selling_price'=>4999,
                'stock'=>15,
                'reorder_level'=>3,
                'status'=>true,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'category_id'=>3,
                'supplier_id'=>4,
                'sku'=>'FUR-0002',
                'name'=>'Computer Desk',
                'description'=>'120cm Wooden Desk',
                'cost_price'=>4200,
                'selling_price'=>5999,
                'stock'=>12,
                'reorder_level'=>3,
                'status'=>true,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'category_id'=>10,
                'supplier_id'=>13,
                'sku'=>'SEC-0001',
                'name'=>'CCTV Camera',
                'description'=>'1080P Security Camera',
                'cost_price'=>2500,
                'selling_price'=>3600,
                'stock'=>18,
                'reorder_level'=>4,
                'status'=>true,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'category_id'=>11,
                'supplier_id'=>12,
                'sku'=>'TOOL-0001',
                'name'=>'Cordless Drill',
                'description'=>'20V Power Drill',
                'cost_price'=>2800,
                'selling_price'=>3999,
                'stock'=>14,
                'reorder_level'=>4,
                'status'=>true,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'category_id'=>12,
                'supplier_id'=>12,
                'sku'=>'ELEC-0003',
                'name'=>'Extension Cord',
                'description'=>'5 Meter Extension',
                'cost_price'=>250,
                'selling_price'=>399,
                'stock'=>80,
                'reorder_level'=>20,
                'status'=>true,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'category_id'=>14,
                'supplier_id'=>7,
                'sku'=>'PRINT-0001',
                'name'=>'HP Laser Printer',
                'description'=>'Mono Laser Printer',
                'cost_price'=>6800,
                'selling_price'=>8500,
                'stock'=>8,
                'reorder_level'=>2,
                'status'=>true,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'category_id'=>15,
                'supplier_id'=>18,
                'sku'=>'MOB-0001',
                'name'=>'Samsung Galaxy Tab',
                'description'=>'Android Tablet',
                'cost_price'=>12000,
                'selling_price'=>14999,
                'stock'=>10,
                'reorder_level'=>2,
                'status'=>true,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'category_id'=>16,
                'supplier_id'=>14,
                'sku'=>'AUD-0001',
                'name'=>'Bluetooth Speaker',
                'description'=>'Portable Speaker',
                'cost_price'=>900,
                'selling_price'=>1499,
                'stock'=>35,
                'reorder_level'=>8,
                'status'=>true,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'category_id'=>17,
                'supplier_id'=>16,
                'sku'=>'CAB-0001',
                'name'=>'HDMI Cable',
                'description'=>'2 Meter HDMI Cable',
                'cost_price'=>120,
                'selling_price'=>250,
                'stock'=>100,
                'reorder_level'=>20,
                'status'=>true,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'category_id'=>18,
                'supplier_id'=>15,
                'sku'=>'LIGHT-0001',
                'name'=>'LED Bulb 12W',
                'description'=>'Energy Saving Bulb',
                'cost_price'=>80,
                'selling_price'=>150,
                'stock'=>150,
                'reorder_level'=>30,
                'status'=>true,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'category_id'=>19,
                'supplier_id'=>13,
                'sku'=>'SAFE-0001',
                'name'=>'First Aid Kit',
                'description'=>'Complete Emergency Kit',
                'cost_price'=>500,
                'selling_price'=>799,
                'stock'=>25,
                'reorder_level'=>5,
                'status'=>true,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'category_id'=>20,
                'supplier_id'=>20,
                'sku'=>'MISC-0001',
                'name'=>'Label Stickers',
                'description'=>'Inventory Labels',
                'cost_price'=>50,
                'selling_price'=>120,
                'stock'=>300,
                'reorder_level'=>50,
                'status'=>true,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
        ]);
    }
}